### ISSUE TITLE
Discussion: should `--debug` and `--verbose` be removed?

### ISSUE THREAD

**Issue by jyn514** [deadlinks/cargo-deadlinks#92]
Right now, these are the only two places where `--debug` and `--verbose` are used: https://github.com/deadlinks/cargo-deadlinks/blob/5af27cd5b4a2ce9c21b38053461ae007e645192f/src/main.rs#L116-L126
https://github.com/deadlinks/cargo-deadlinks/blob/5af27cd5b4a2ce9c21b38053461ae007e645192f/src/main.rs#L191-L195

This seems a little silly, since the user can set RUST_LOG themselves using env_logger. In particular, it means that currently RUST_LOG does nothing, since deadlinks will override it. Maybe we should leave it up to the user instead?

The 'shorten paths' bit still seems useful, but I'm not sure 'debug' is the right name for it - I'd prefer `--no-abbrev` or something like that I think.

I'd still keep the existing flags, but in the case of `--verbose` warn that it does nothing and for `--debug` warn that you should use `--no-abbrev` instead.

**Comment by hobofan** [comment]
The only intention of these flags was to set the logging level (the other change seems to have come in more recently).

I generally add those flags to CLIs because I don't think it's reasonable to expect from the user of a CLI to try to guess what logging facilities are built into a program and how they can be controlled. If you were to remove `--verbose` from e.g. `curl` would you know that there even is a verbose mode, and what envvar would you use to control it instead?

As for it overriding `RUST_LOG`, I seem to remember that it still works when specifying lower level libs, (like `RUST_LOG=ureq=debug`), but I might be wrong there. If neither flags are specified, it should definitely yield control to `RUST_LOG`.

**Comment by jyn514** [comment]
> I generally add those flags to CLIs because I don't think it's reasonable to expect from the user of a CLI to try to guess what logging facilities are built into a program and how they can be controlled. If you were to remove --verbose from e.g. curl would you know that there even is a verbose mode, and what envvar would you use to control it instead?

Got it, that makes sense. Do you think it be enough to print the env variable in the help message ('use RUST_LOG=cargo_deadlinks to show verbose logging')? Or do you think `--verbose` is good for consistency with other CLI tools?

**Comment by hobofan** [comment]
I personally have a slight preference for keeping it for consistency, but also don't feel too strongly if it's otherwise indicated in some way.

**Comment by jyn514** [comment]
Ok, I'll keep `--verbose` and `--debug` for consistency but give precedence to `RUST_LOG` if neither are passed.
